### ISSUE TITLE
Avoid manual memory management with JSClosure

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/JavaScriptKit#106]
I wonder if [reference types](https://bytecodealliance.org/articles/reference-types-in-wasmtime) could lift our requirement to manage references to JS closures manually?

> With `externref`s, the host gives Wasm limited access to host objects, but the host also needs to know when Wasm is finished with those objects, so it can clean them up. That clean up might involve closing a file handle or simply deallocating memory. 

This means that JS closures should be passed to the Swift code as `externref`. Deallocating all references to `externref` would deallocate the closure on the JS side.

Reference types are now available in all browsers except Safari, and in the latter case they seem to only be hidden behind `JSC_useWebAssemblyReferences` flag. The only question is `externref` support in our toolchain...

Doesn't look like LLVM had much progress in that direction? 🤔 Also see https://github.com/WebAssembly/tool-conventions/issues/122

**Comment by MaxDesiatov** [comment]
Turns out LLVM does have it in some state as introduced in https://github.com/llvm/llvm-project/commit/79aad89d8d29029b4e937137e6b8619ee8a4b691.

**Comment by j-f1** [comment]
IIRC the issue with JSClosure is that when passed to JS APIs, the Swift closure is deallocated early. We could manage this by using a [`FinalizationRegistry`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) to track when it’s safe to free the Swift closure, but that has not yet reached production versions of Safari (it seems to currently be in nightly WebKit only)
