### ISSUE TITLE
Do you accept contributions for wrappers over JavaScript objects?

### ISSUE THREAD

**Issue by revolter** [swiftwasm/JavaScriptKit#124]
For example, would you accept a `JSFileReader` class, similar to [`JSDate`](https://github.com/swiftwasm/JavaScriptKit/blob/main/Sources/JavaScriptKit/BasicObjects/JSDate.swift), which would wrap [`FileReader`](https://developer.mozilla.org/en-US/docs/Web/API/FileReader)?

**Comment by j-f1** [comment]
IMO JavaScriptKit should only contain portable classes — ones that would work in most (if not all) JS environments. DOM-specific types like `FileReader` would be better off in DOMKit, which is in need of finishing, if you’re interested.

**Comment by MaxDesiatov** [comment]
I agree, JavaScriptKit is only supposed to wrap APIs that are available across all JavaScript runtimes, including Node.js. [DOMKit](https://github.com/swiftwasm/DOMKit) is a better fit for browser-specific stuff, and there we try to get these wrappers automatically generated. I don't remember if `FileReader` is covered by our codegen off the top of my head...

**Comment by j-f1** [comment]
Here’s `FileReader`: https://github.com/swiftwasm/DOMKit/blob/e45d37fbfddbe982a612f577d41ade85bab1bfbc/Sources/DOMKit/WebIDL/FileReader.swift

**Comment by revolter** [comment]
Amazing! You are the best maintainers in the world ❤️
