### ISSUE TITLE
Use FinalizationRegistry to auto-deinit Closures

### ISSUE THREAD

**Issue by nmn** [swiftwasm/JavaScriptKit#131]
There is a new-ish JS API called [FinalizationRegistry](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) that lets you add a finalization callback to values in Javascript that gets run sometime after a value is Garbage Collected in Javascript.

Together with `WeakRef`, this API could be used to automatically `release`/`deinit` JSClosures which currently need to managed manually.

Here's an article describing it's use within JS: https://v8.dev/features/weak-references
Another article describing it's use for Wasm/Wasi: https://rob-blackbourn.github.io/blog/webassembly/wasm/wasi/javascript/c/clang/wasi-sdk/marshalling/finalizer/finalizationregistry/2020/07/07/wasi-finalizers-1.html

There is probably some cost associated with using this API, so I don't think that *all* JSClosures should have this behaviour. Frameworks such as Tokamak can probably handle event listeners just fine, but in other cases it would make things much easier.

The feature is supported in all modern browsers (including Safari 14.1 +)

**Comment by carson-katri** [comment]
@j-f1 has a PR to implement this I believe at #128

**Comment by j-f1** [comment]
Ooh interesting idea: I could restore the old closure behavior as `JSUnmanagedClosure`, with the plain `JSClosure` throwing if it’s unsupported.

**Comment by j-f1** [comment]
Implemented in #128
