### ISSUE TITLE
Enchancement: Add a link to the docs 

### ISSUE THREAD

**Issue by jhoughjr** [swiftwasm/JavaScriptKit#136]
I found some nice docs for this from a link in the SwiftWasm book.
I think it would help if the link were here as well in the README.

The link is https://swiftwasm.github.io/JavaScriptKit/

**Comment by j-f1** [comment]
They’re currently linked from the repo homepage (https://github.com/swiftwasm/JavaScriptKit) right under the description.

**Comment by jhoughjr** [comment]
I visually inspected twice and found no link. 
I looked again and still find no links to documentation at the location you gave.
There is example code, info on installing but nothing like the documentation that is at the link I provided.

**Comment by carson-katri** [comment]
I’m seeing it there
![0E1CFF85-02E2-461A-8C67-4C3043A04845](https://user-images.githubusercontent.com/13581484/129965794-7667affa-7f44-4f49-a0e6-1626d5b7990b.jpeg)

**Comment by jhoughjr** [comment]
I see it now.
Thats why im legally blind I suoppose.
