### ISSUE TITLE
Arguments in JSClosure

### ISSUE THREAD

**Issue by mhavu** [swiftwasm/JavaScriptKit#155]
How is one supposed to use arguments in `JSClosure`? Is it necessary to unpack them manually from the `JSValue` array? If I try to do that, I get an error message about ambiguous use of `subscript(dynamicMember:)`:
```swift
JSClosure { (arguments: [JSValue]) in
    guard let item = arguments.first,  let deviceId = item.string else {
        // item in item.string causes error: ambiguous use of 'subscript(dynamicMember:)'
        return .undefined
    }
    // ...
}
```

**Comment by j-f1** [comment]
What Xcode/Swift version are you using? On Xcode 13.2.1 (swift 5.5), I’m seeing that code build without errors.

**Comment by mhavu** [comment]
I have Xcode 13.2.1 (build version 13C100) and SwiftWasm 5.5.

**Comment by j-f1** [comment]
With this code, I get no errors (just a warning about variables being unused):


```swift
import JavaScriptKit

public struct test {
    public init() {
        let closure = JSClosure { (arguments: [JSValue]) in
            guard let item = arguments.first,  let deviceId = item.string else {
                // item in item.string causes error: ambiguous use of 'subscript(dynamicMember:)'
                return .undefined
            }
            return .number(42)
        }
    }
}
```

**Comment by mhavu** [comment]
Thanks. Going through the cases one by one, I noticed that the problem was not with `item` but a typo in the member name after that (`string` in this case). By chance, I had picked the only one that actually worked in this case. 🤦‍♂️
