### ISSUE TITLE
JSPromise(resolver:) usage

### ISSUE THREAD

**Issue by mhavu** [swiftwasm/JavaScriptKit#156]
Could somebody provide an example of how to use `JSPromise(resolver:)`? I'm having hard time decoding the following comment in the source code:
> Creates a new `JSPromise` instance from a given `resolver` closure. `resolver` takes two closure that your code should call to either resolve or reject this `JSPromise` instance.

**Comment by mhavu** [comment]
Never mind. Using a closure in the constructor worked just as one would expect:
```swift
JSPromise { (resolve, reject) in
    // ...
}
```

**Comment by j-f1** [comment]
Those docs look to be outdated. (if you could open a PR to clarify them that would be awesome!) You’re actually passed one callback closure that takes a `Result` type. If you pass it a `.success(...)` value, the promise will resolve with that value. If you pass it a `.failure(...)` value, the promise will reject with that error.

**Comment by mhavu** [comment]
Thanks! I'll open a PR once I get this project out of the way.

**Comment by j-f1** [comment]
Going to make a couple other improvements to the JSPromise docs so will handle this myself :)
