### ISSUE TITLE
Asynchronous calls in JSClosure

### ISSUE THREAD

**Issue by mhavu** [swiftwasm/JavaScriptKit#157]
What is the best way to handle calls to asynchronous code inside a `JSClosure`, especially if one needs to return the result of such call from the `JSClosure`? Consider the following example:
```swift
let closure = .object(JSClosure { (arguments: [JSValue]) in
    guard let url = arguments.first?.string else {
        return JSValue.undefined
    }
    return await fetch(url)
})
```
This results in the following error:
> cannot pass function of type '([JSValue]) async -> JSValue' to parameter expecting synchronous function type

The reason is obvious, but is there a nice way to work around this?

**Comment by j-f1** [comment]
That would be a great feature to add! I would imagine it as either an overload of `JSClosure.init` that takes an `async` closure, or a separate `JSClosure.async` static method (for clarity) that does something like this:

```swift
static func async(_ body: @escaping ([JSValue]) async throws -> JSValue) -> JSClosure {
    JSClosure { arguments in
        JSPromise { resolver in
            Task {
                do {
                    let result = try await body(arguments)
                    resolver(.success(result))
                } catch {
                    if let jsError = error as? JSError {
                        resolver(.failure(jsError.jsValue()))
                    } else {
                        resolver(.failure(JSError(message: String(describing: error)).jsValue()))
                    }
                }
            }
        }.jsValue()
    }
}
```

**Comment by mhavu** [comment]
Indeed. If one doesn't need to return the result of the asynchronous call, using `Task` inside a `JSClosure` should work as it is, right? If this is the case, wrapping the asynchronous call (inside `Task`) to a synchronous function that calls a completion handler should do the trick when the result needs to be returned. What you suggest above would definitely be cleaner.

**Comment by j-f1** [comment]
I don’t think that code would work. Specifically, I get two compiler errors: “Variable 'result' captured by a closure before being initialized” and “Variable 'result' used before being initialized.” However, you’re correct that if you don’t need to return the result of the asynchronous call (and if you don’t need the JS code to be able to wait for your code to finish running), running the async code in a `Task` would work.

**Comment by mhavu** [comment]
Ah, too bad. Now that you mention it, it is clear that the closure can reach the `return` statement before the completion handler has set the result.

**Comment by mhavu** [comment]
This does indeed work:
```swift
let closure = .object(JSClosure { (arguments: [JSValue]) in
    guard let url = arguments.first?.string else {
        return JSValue.undefined
    }
    func wrappedFetch(_ url: String, completion: @escaping (String) -> ()) {
        Task {
            let data = try await fetch(url)
            completion(data)
        }    
    }
    let result = JSPromise { resolve in
         wrappedFetch(url) { data in
            resolve(.success(data))
        }
    }
    return result.jsValue()
})
```
