### ISSUE TITLE
Accessing localStorage fails

### ISSUE THREAD

**Issue by carson-katri** [swiftwasm/JavaScriptKit#18]
Here's a simple example:
```swift
let localStorage = JSObjectRef.global.localStorage.object!
print(localStorage.getItem!("hello"))
_ = localStorage.setItem!("hello", "world")
print(localStorage.getItem!("hello"))
```
Prints `null` then `.string("world")` as expected.

However, if you refresh the site after the value is set, it crashes with `Reflect.get called on non-object`.

**Comment by kateinoigakukun** [comment]
@carson-katri Thanks for reporting! Could you try this branch https://github.com/swiftwasm/JavaScriptKit/pull/19 ?

**Comment by carson-katri** [comment]
Sorry, same crash 😕

**Comment by kateinoigakukun** [comment]
@carson-katri  Hmm, did you reference local runtime library in this repo instead of the released runtime library?
I think you may be using version 0.4.0. Please specify local built runtime library following these steps.

1. Build runtime library on your machine
```sh
$ pwd
path/to/JavaScriptKit
$ cd Runtime && npm run build
```

2. Update your package.json

```diff
{
  ...
  "dependencies": {
    ...
-    "javascript-kit-swift": "0.4.0"
+    "javascript-kit-swift": "file:path/to/JavaScriptKit/Runtime"
  },
  ...
}
```

3. Update your Package.swift

```diff
let package = Package(
    ...
-    .package(url: "https://github.com/kateinoigakukun/JavaScriptKit.git", .revision("master")),
+    dependencies: [.package(name: "JavaScriptKit", path: "path/to/JavaScriptKit")],
    ...
)
```

**Comment by MaxDesiatov** [comment]
I assume, if the project is built with `carton` it uses the runtime shipped with the `dev` entrypoint: https://github.com/swiftwasm/carton/blob/main/package.json

**Comment by MaxDesiatov** [comment]
Most probably easier to test that branch without `carton`, maybe through some custom `webpack` project.

**Comment by carson-katri** [comment]
Got it working, thanks!
