### ISSUE TITLE
DOMKit?

### ISSUE THREAD

**Issue by j-f1** [swiftwasm/JavaScriptKit#21]
It would be great to have some sort of type-safe DOM API that better matches DOM as exposed to JS (for example `document.querySelector('foo')?.appendChild(document.createElement('bar'))`) without having to go through the ceremony of `.object!` and `.function!`. It looks like there’s some work in this direction in [`webidl2swift`](https://github.com/Apodini/webidl2swift) but I’m not sure how much more is needed.

**Comment by MaxDesiatov** [comment]
Generating the `WebAPI` module as described [in the `webidl2swift` example](https://github.com/Apodini/webidl2swift/tree/develop/Example) worked for me, but they have a dependency on [a fork of JavaScriptKit](https://github.com/Unkaputtbar/JavaScriptKit/commit/8f0a15464238781a90141b93558d79c14d101bd5). I think upstreaming changes from that fork could be the first step.

**Comment by j-f1** [comment]
I tried to merge but it seems like they made a bunch of unrelated changes in the fork which seem vaguely like a good idea since they reduce memory usage (I think) and cut down on the number of arguments that need to be passed around on the JS side but that means it’s hard to extract just the new stuff

**Comment by j-f1** [comment]
I’ve got DOMKit building! (haven’t tried running it yet)

https://github.com/j-f1/DOMKit

```swift
let document = DOMKit.Document(jsValue: JSObjectRef.global.document)

let button = document.createElement(localName: "button")
button.textContent = "Hello, world"

class ClickListener: EventListener {
    required init(objectRef: JSObjectRef) {
        self.objectRef = objectRef
    }

    var objectRef: JSObjectRef
    static func canDecode(from jsValue: JSValue) -> Bool { false }
    func handleEvent(event: Event) {
        (event.target as? HTMLElement)?.textContent = "Clicked!"
    }
}

let emptyObject = JSObjectRef.global.Object.function!(.new)

button.addEventListener(type: "click", callback: ClickListener(objectRef: emptyObject))
_ = document.querySelector(selectors: "body")?.appendChild(node: button)
```

**Comment by j-f1** [comment]
While this is a start, several changes are needed for a truly great native swift DOM API￼. We need to be able to modify the default function signatures to change or remove parameter names. Well some named parameters would be a great addition to the usability of the DOM API, I think that most of them provide little benefit￼. Dude also be great to extend the DON API with methods that make use of native Swift types and best practices.￼ For example, options that are passed as an object in JavaScript could be expanded out to named parameters in Swift.￼ It would also be good to allow passing Swift closures as an event handler, as the current way of creating a event handler object is extremely cumbersome.￼

**Comment by j-f1** [comment]
With a ton of tweaks, I have got it working again with perhaps fewer changes!

**Comment by MaxDesiatov** [comment]
Closing this as we got it working more or less, appropriate discussions should happen in the DOMKit repository https://github.com/swiftwasm/DOMKit
