### ISSUE TITLE
Compiled module was created by a different version of the compiler; rebuild 'JavaScriptKit' and try again

### ISSUE THREAD

**Issue by TeamPuzel** [swiftwasm/JavaScriptKit#212]
Hi,
On the latest version of Xcode adding JavaScriptKit as a dependency for a Swift package and importing it causes this error.

**Comment by kateinoigakukun** [comment]
Please clean DerivedData and build again

**Comment by TeamPuzel** [comment]
hmm okay that solved it thanks, though not even the examples actually compile, and carton crashes
