### ISSUE TITLE
JSClosure will be overriden from other closure

### ISSUE THREAD

**Issue by sidepelican** [swiftwasm/JavaScriptKit#218]
JSClosure stores its identifier and tell it to JS for bridging, but the identifiers has a trouble.
`hashValue` is used for the identifier, but `hashValue` is not guaranteed to be unique.

https://github.com/swiftwasm/JavaScriptKit/blob/1afbfaf16598119a851dca39e3b447de6cf52589/Sources/JavaScriptKit/FundamentalObjects/JSClosure.swift#L89

**Comment by j-f1** [comment]
Hm, good point! Looking at [the relevant implementations](https://github.com/apple/swift/blob/main/stdlib/public/core/ObjectIdentifier.swift) I think that should be replaced with the `UInt(bitPattern:)` initializer which can take an `ObjectIdentifier`.
