### ISSUE TITLE
`Int.construct(from:)` can crash instead of return `nil`

### ISSUE THREAD

**Issue by stephencelis** [swiftwasm/JavaScriptKit#258]
While the `JSValueCompatible` APIs are failable, the underlying conversion of calling `SignedInteger.init(_:)` and `UnsignedInteger.init(_:)` [directly](
https://github.com/swiftwasm/JavaScriptKit/blob/396ff4519d30561d9a7589dfb022739af2e1a9e6/Sources/JavaScriptKit/ConstructibleFromJSValue.swift#L43) can crash at runtime if:

- `double.isNan`
- `!double.isFinite`
- `double > .max || double < .min`

Ideally, none of these would crash and return `nil` instead:

- `Int.construct(from: JSValue.number(.infinity))`
- `Int.construct(from: JSValue.number(.nan))`
- `Int.construct(from: JSValue.number(numberGreaterThanIntMax)`
- `Int.construct(from: JSValue.number(numberLessThanIntMin)`

**Comment by stephencelis** [comment]
I think this would suffice:

```diff
-return Self(number)
+return Self(exactly: number.rounded(.towardZero))
```

**Comment by kateinoigakukun** [comment]
Thanks for reporting!
