### ISSUE TITLE
BigInt Support

### ISSUE THREAD

**Issue by j-f1** [swiftwasm/JavaScriptKit#29]
As part of #26, I created an API that uses BigInt values in some cases. They are not currently implemented, however. An important design question is whether bey should be represented as Int64/UInt64 — sacrificing precision for code size and ease of use — or whether some sort of [BigInt](https://github.com/attaswift/BigInt) library should be made a dependency so we can guarantee precision at the cost of code size and performance.

**Comment by kateinoigakukun** [comment]
[js-api spec](https://webassembly.github.io/spec/js-api/) says BigInt is coerced to wasm types (i32, i64, f32, f64). So we don't need to care over 64bits case.
