### ISSUE TITLE
TypedArray improvement?

### ISSUE THREAD

**Issue by j-f1** [swiftwasm/JavaScriptKit#52]
Currently, creating a TypedArray using `swjs_create_typed_array` requires passing an enumerated value, `JavaScriptTypedArrayKind`, to determine which kind of typed array should be created. I don’t remember exactly why I did this — would it make more sense to just pass a reference to the constructor function for the particular typed array we want?

**Comment by kateinoigakukun** [comment]
It seems better way. 👍
