### ISSUE TITLE
Build fails with the unsafe flags error

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/JavaScriptKit#6]
I have a very trivial app [here](https://github.com/MaxDesiatov/carton/tree/master/TestApp) that depends on JavaScriptKit, but it fails to build with this error:

```
% swift build --triple wasm32-unknown-wasi                                     
error: the target 'JavaScriptKit' in product 'JavaScriptKit' contains unsafe build flags
% swiftenv version
wasm-DEVELOPMENT-SNAPSHOT-2020-05-02-a (set by /Users/maxd/Documents/carton/TestApp/.swift-version)
% which swift
/Users/maxd/.swiftenv/shims/swift
% swift --version
Swift version 5.3-dev (LLVM 11086900c5, Swift 52a06ad8f3)
Target: x86_64-apple-darwin19.4.0
```

**Comment by kateinoigakukun** [comment]
Yes, you can't use a tag to specify a fixed revision due to unsafe flags.
So you need to specify a commit hash to fix revision like [here](https://github.com/swiftwasm/swift-webpack-template/blob/master/Package.swift#L12)

But in the long run, we need to support these flags safely in SwiftPM.

**Comment by MaxDesiatov** [comment]
I think this becomes a higher priority as it prevents any projects that depend on JavaScriptKit from being built for any platform other than non-WASI. For example, it's currently blocking https://github.com/TokamakUI/Tokamak/pull/276.

The big problem is that it may require changes to the package manifest API, such as new safe linker settings. Any new settings won't be available on non-WASI platforms until the next version of Swift is released. If we add new linker settings, they definitely need to land upstream before the next version is branched off, but I think we also need to find some workaround in the meantime.

**Comment by MaxDesiatov** [comment]
Here's a possible solution that I proposed in the `#webassembly` channel of SwiftPM Slack:

1. For SwiftWasm 5.3 we could hardcode the flags and apply them in our forked SwiftPM if target/product name is JavaScriptKit. We then remove unsafe flags from `Package.swift` in JavaScriptKit as our forked SwiftPM would know how to build it anyway. We already [have an ugly hardcoded check](https://github.com/swiftwasm/swift-package-manager/blob/swiftwasm-release/5.3/Sources/PackageGraph/PackageGraphLoader.swift#L544) in our fork to allow unsafe flags in JavaScriptKit anyway.
2. For future versions of Swift either apple/swift-package-manager#2749 resolves the issue, or we need to submit more PRs upstream that allow specifying export linker flags safely with new `linkerSettings` cases in `Package.swift`.
