### ISSUE TITLE
Automatic performance testing

### ISSUE THREAD

**Issue by j-f1** [swiftwasm/JavaScriptKit#67]
I’ve seen repositories before that have a bot post a comment on all new PRs with a comparison of the perf tests between `main` and the PR branch. This would be very nice to have so we don’t accidentally introduce regressions, and to celebrate perf improvements when they’re added.

**Comment by j-f1** [comment]
Here’s an action that could probably be adapted to measure perf instead of bundle size: https://github.com/preactjs/compressed-size-action/blob/master/src/index.js

**Comment by MaxDesiatov** [comment]
Can this be considered resolved now?
