### ISSUE TITLE
Documentation website is broken

### ISSUE THREAD

**Issue by kateinoigakukun** [swiftwasm/JavaScriptKit#93]
It seems CSS style is not applied at all.

https://github.com/swiftwasm/JavaScriptKit/blob/gh-pages/all.css

CC: @MaxDesiatov

**Comment by j-f1** [comment]
Looks like it got wiped out by the most recent deploy: https://github.com/swiftwasm/JavaScriptKit/commit/0e60acfe7c587df62f5837d6bf8fd0d6363434ac#diff-889b5374b13d0504888431f3656f6bdc

**Comment by MaxDesiatov** [comment]
Sorry about that, I'll be able to have a look at it later today or tomorrow, unless someone discovers a fix earlier than me by that point.

**Comment by MaxDesiatov** [comment]
Reported as https://github.com/SwiftDocOrg/swift-doc/issues/198, still investigating...

**Comment by MaxDesiatov** [comment]
Mattt tagged a new release, and I've redeployed the docs with it. All looks fine now.

**Comment by mattt** [comment]
@MaxDesiatov Again, my sincere apologies for breaking your documentation workflow. I'm working to make sure that never happens again. Thanks for your contributions to and early adoption of swift-doc.

**Comment by MaxDesiatov** [comment]
No problem at all @mattt, I appreciate your hard work, and I hope I can contribute more to `swift-doc` myself to help you going forward!
